insert into Usuario (nome , sobrenome , email , username , password) values ('Vittoria' , 'Sacker'   , 'vsacker0@shareasale.com' , 'vsacker0'  , md5(concat('IcBCOJbyp2','vsacker0')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Gayelord' , 'Stigers'  , 'gstigers1@youtube.com'   , 'gstigers1' , md5(concat('3Q05V2Y','gstigers1')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Ebonee'   , 'Foote'    , 'efoote2@ocn.ne.jp'       , 'efoote2'   , md5(concat('ZEm1VKtLnF','efoote2')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Savina'   , 'Brik'     , 'sbrik3@chron.com'        , 'sbrik3'    , md5(concat('xVOPZAR5J4J','sbrik3')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Rani'     , 'Doret'    , 'rdoret4@omniture.com'    , 'rdoret4'   , md5(concat('6tp5NCBl','rdoret4')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Simonne'  , 'McGuirk'  , 'smcguirk5@tumblr.com'    , 'smcguirk5' , md5(concat('MZNhRkVNiA','smcguirk5')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Eilis'    , 'Tommasi'  , 'etommasi6@narod.ru'      , 'etommasi6' , md5(concat('qeGmxNKNM8a','etommasi6')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Yvor'     , 'de Pinna' , 'ydepinna7@w3.org'        , 'ydepinna7' , md5(concat('wroQw0YYGKL','ydepinna7')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Myrwyn'   , 'Lavin'    , 'mlavin8@irs.gov'         , 'mlavin8'   , md5(concat('e6ZQF0xG7tQ','mlavin8')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Jamie'    , 'Lear'     , 'jlear9@cpanel.net'       , 'jlear9'    , md5(concat('oVQKlvcq','jlear9')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Kania'    , 'Esparza'  , 'kesparzaa@smugmug.com'   , 'kesparzaa' , md5(concat('735AuUCH2l','kesparzaa')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Althea'   , 'Velden'   , 'aveldenb@tiny.cc'        , 'aveldenb'  , md5(concat('k2FFz5mx2yk','aveldenb')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Jerrilyn' , 'Alben'    , 'jalbenc@bing.com'        , 'jalbenc'   , md5(concat('MN1T4Vytn','jalbenc')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Melissa'  , 'Samper'   , 'msamperd@desdev.cn'      , 'msamperd'  , md5(concat('dUuMGvprueC','msamperd')));
insert into Usuario (nome , sobrenome , email , username , password) values ('Raddie'   , 'Senton'   , 'rsentone@phpbb.com'      , 'rsentone'  , md5(concat('TuXkJYBxigWd','rsentone')));
